// DO NOT EDIT: This file is automatically generated.
//
// Only the associated template file should be edited directly.
// Helper class files are automatically regenerated from the template
// files at various times, including record actions and test object
// insertion actions.  Any changes made directly to a helper class
// file will be lost when automatically updated.

package resources;

import com.rational.test.ft.object.interfaces.*;
import com.rational.test.ft.object.interfaces.SAP.*;
import com.rational.test.ft.object.interfaces.WPF.*;
import com.rational.test.ft.object.interfaces.siebel.*;
import com.rational.test.ft.object.interfaces.flex.*;
import com.rational.test.ft.object.interfaces.dojo.*;
import com.rational.test.ft.object.interfaces.generichtmlsubdomain.*;
import com.rational.test.ft.script.*;
import com.rational.test.ft.vp.IFtVerificationPoint;
import com.ibm.rational.test.ft.object.interfaces.sapwebportal.*;
/**
 * Script Name   : <b>AXA_RFT_POC_TestScript_Batch_WC3270</b><br>
 * Generated     : <b>2017/09/26 11:12:59 PM</b><br>
 * Description   : Helper class for script<br>
 * Original Host : Windows 7 x86 6.1 <br>
 * 
 * @since  September 26, 2017
 * @author jonathan.h.francisco
 */
public abstract class AXA_RFT_POC_TestScript_Batch_WC3270Helper extends RationalTestScript
{
	/**
	 * MainframeWc3270: with default state.
	 *		.text : Mainframe - wc3270
	 * 		.class : ConsoleWindowClass
	 * 		.processName : wc3270.exe
	 * 		.name : Mainframe - wc3270
	 */
	protected TopLevelSubitemTestObject WC3270Window() 
	{
		return new TopLevelSubitemTestObject(
                        getMappedTestObject("WC3270Window"));
	}
	/**
	 * MainframeWc3270: with specific test context and state.
	 *		.text : Mainframe - wc3270
	 * 		.class : ConsoleWindowClass
	 * 		.processName : wc3270.exe
	 * 		.name : Mainframe - wc3270
	 */
	protected TopLevelSubitemTestObject WC3270Window(TestObject anchor, long flags) 
	{
		return new TopLevelSubitemTestObject(
                        getMappedTestObject("WC3270Window"), anchor, flags);
	}
	
	/**
	 * Locate and return the verification point MainframeWc3270_standard object in the SUT.
	 */
	protected IFtVerificationPoint MainframeWc3270_standardVP() 
	{
		return vp("MainframeWc3270_standard");
	}
	protected IFtVerificationPoint MainframeWc3270_standardVP(TestObject anchor)
	{
		return vp("MainframeWc3270_standard", anchor);
	}
	
	

	protected AXA_RFT_POC_TestScript_Batch_WC3270Helper()
	{
		setScriptName("AXA_RFT_POC_TestScript_Batch_WC3270");
	}
	
}

